theme: jekyll-theme-minimal
title: 珩妈的数学启蒙乐园
description: 在游戏中探索数学的奇妙世界！

# 基础设置 - 针对 windermazhang.github.io 仓库
baseurl: "/mini_game"  # 因为游戏文件在 mini_game 子目录中
url: "https://windermazhang.github.io"

# 处理游戏文件
include:
  - games

# 排除不需要的文件
exclude:
  - .DS_Store
  - README.md
  - .git
  - "游戏开发计划.md"

# 游戏特定设置
defaults:
  - scope:
      path: "games"
    values:
      layout: none
